# Generated by Django 4.0.3 on 2023-03-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='test2',
            new_name='phonenumber',
        ),
    ]
