# Generated by Django 4.0.3 on 2023-03-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_test_user_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
