# Generated by Django 4.0.3 on 2023-03-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_user_phonenumber_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
